name: Ubuntu

on: 
  push:
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  c_cxx:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler:
          - { cpp: g++-12, c: gcc-12}
          - { cpp: g++-13, c: gcc-13}
          - { cpp: g++-14, c: gcc-14}
          - { cpp: clang++, c: clang}
        build_type: [Release]
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev build-essential
          sudo apt-get install -y python3-numpy

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D MUSICA_ENABLE_TUVX=OFF -D MUSICA_ENABLE_PYTHON_LIBRARY=ON

      - name: Build
        run: cmake --build build --verbose --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose -j 10
  fortran:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gcc_version: [12, 13, 14]
        build_type: [Release]
    env:
      CXX: g++-${{ matrix.gcc_version }}
      CC: gcc-${{ matrix.gcc_version }}
      FC: gfortran-${{ matrix.gcc_version }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev netcdf-bin libnetcdff-dev liblapack-dev libblas-dev

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D MUSICA_BUILD_FORTRAN_INTERFACE=ON

      - name: Build
        run: cmake --build build --verbose --parallel 1

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose -j 10